#!/bin/python3

import sys
import os



# Add Celsius class implementation below.
class Celsius(object):
    def __init__(self,value=0.0): 
        self.value = float(value)
    def __get__(self,instance,owner):
        return self.value
    def __set__(self,instance,value):
        self.value =  value

# Add temperature class implementation below.
class Fahrenheit(object):
    def __init__(self,value=0.0): 
        self.fahrenheit = value  
        celsius = Celsius()  
    def __set__(self, instance, value):
        instance.celsius = (float(value)-32)*5/9 
    def __get__(self, instance, owner):
        return instance.celsius*9/5 -32
class Temperature ():
    celsius = Celsius()
    fahrenheit = Fahrenheit()
        
'''Check the Tail section for input/output'''

if __name__ == "__main__":
    with open(os.environ['OUTPUT_PATH'], 'w') as fout:
        res_lst = list()
        t1 = Temperature(int(input()))
        res_lst.append((t1.fahrenheit, t1.celsius))
        t1.celsius = int(input())
        res_lst.append((t1.fahrenheit, t1.celsius))
        fout.write("{}\n{}".format(*res_lst))
